coverage:
  acceptable: current >= 0%
  paths:
    - lcov.info 
  badge:
    path: assets/server-coverage.svg
codeToTestRatio:
  code:
    - 'server/**/*.py'
    - '!server/test/**/test_*.py'
  test:
    - 'server/test/**/test*.py'
  badge:
    path: assets/server-ratio.svg
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
push:
comment:
  if: is_pull_request
  deletePrevious: true
summary:
  if: is_default_branch
report:
  if: is_default_branch
  path: report.json
  datastores:
    - artifact://${GITHUB_REPOSITORY}
