name: CI/CD with Octocov

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Install Dependencies
      run: |
        brew install lcov
        gem install slather # To generate lcov report

    - name: Build and Run Tests
      run: |
        xcodebuild test \
          -scheme "ebuddy" \
          -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
          -derivedDataPath build \
          -enableCodeCoverage YES
      env:
        CI: true

    - name: Generate lcov Report
      run: |
        slather coverage --input-format profdata --output-format lcov \
          --scheme ebuddy --workspace ebuddy.xcworkspace --build-directory build build/ebuddy.xcodeproj
        mv build/lcov.info lcov.info

    - name: Debug lcov Report
      run: |
        echo "Generated lcov.info:"
        cat lcov.info

    - name: Report Coverage
      uses: k1LoW/octocov-action@v1